//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAdvertisementPortal.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertInterestMapper_tbl
    {
        public int InterestID { get; set; }
        public int EmpId { get; set; }
        public int AdvId { get; set; }
    
        public virtual AdvertisementDetails_tbl AdvertisementDetails_tbl { get; set; }
        public virtual EmployeeDetails_tbl EmployeeDetails_tbl { get; set; }
    }
}
