//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAdvertisementPortal.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisementDetails_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdvertisementDetails_tbl()
        {
            this.AdvertInterestMapper_tbl = new HashSet<AdvertInterestMapper_tbl>();
        }
    
        public int AdvId { get; set; }
        public int EmpId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public System.DateTime PostedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Location { get; set; }
        public int AdvCategoryId { get; set; }
        public bool IsApproved { get; set; }
        public bool IsRejected { get; set; }
        public string MediaPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvertInterestMapper_tbl> AdvertInterestMapper_tbl { get; set; }
        public virtual AdvertisementCategory_tbl AdvertisementCategory_tbl { get; set; }
        public virtual EmployeeDetails_tbl EmployeeDetails_tbl { get; set; }
    }
}
