//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAdvertisementPortal.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisementCategory_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdvertisementCategory_tbl()
        {
            this.AdvertisementDetails_tbl = new HashSet<AdvertisementDetails_tbl>();
        }
    
        public int AdvCategoryId { get; set; }
        public string Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvertisementDetails_tbl> AdvertisementDetails_tbl { get; set; }
    }
}
