//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAdvertisementPortal.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserRole_tbl()
        {
            this.EmployeeDetails_tbl = new HashSet<EmployeeDetails_tbl>();
        }
    
        public int RoleId { get; set; }
        public string Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeDetails_tbl> EmployeeDetails_tbl { get; set; }
    }
}
