//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAdvertisementPortal.Core.APILinks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
   public class APIUrl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APIUrl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeAdvertisementPortal.Core.APILinks.APIUrl", typeof(APIUrl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/Approve/.
        /// </summary>
        public static string ApproveAdvertisement {
            get {
                return ResourceManager.GetString("ApproveAdvertisement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/CheckAdvIdExists?id=.
        /// </summary>
        public static string CheckAdvIdExists {
            get {
                return ResourceManager.GetString("CheckAdvIdExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/CheckEmpIdExists?id=.
        /// </summary>
        public static string CheckEmpIdExists {
            get {
                return ResourceManager.GetString("CheckEmpIdExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/CreateAdvertisement.
        /// </summary>
        public static string CreateAdvertisement {
            get {
                return ResourceManager.GetString("CreateAdvertisement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/CreateEmployee.
        /// </summary>
        public static string CreateEmployee {
            get {
                return ResourceManager.GetString("CreateEmployee", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/DeleteAdvertisement/.
        /// </summary>
        public static string DeleteAdvertise {
            get {
                return ResourceManager.GetString("DeleteAdvertise", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/DeleteAdvertise/.
        /// </summary>
        public static string DeleteAdvertisement {
            get {
                return ResourceManager.GetString("DeleteAdvertisement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/DeleteEmployee/.
        /// </summary>
        public static string DeleteEmployee {
            get {
                return ResourceManager.GetString("DeleteEmployee", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/GetAdvertisementById/.
        /// </summary>
        public static string GetAdvertisementById {
            get {
                return ResourceManager.GetString("GetAdvertisementById", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/AdvApprovalList.
        /// </summary>
        public static string GetAdvertisementRequests {
            get {
                return ResourceManager.GetString("GetAdvertisementRequests", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/GetAdvertisementList.
        /// </summary>
        public static string GetAllAdvertisement {
            get {
                return ResourceManager.GetString("GetAllAdvertisement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/Index.
        /// </summary>
        public static string GetAllEmployee {
            get {
                return ResourceManager.GetString("GetAllEmployee", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/GetApprovedList.
        /// </summary>
        public static string GetApprovedList {
            get {
                return ResourceManager.GetString("GetApprovedList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/GetEmployeeById/.
        /// </summary>
        public static string GetEmployeeById {
            get {
                return ResourceManager.GetString("GetEmployeeById", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/Reject/.
        /// </summary>
        public static string RejectAdvertisement {
            get {
                return ResourceManager.GetString("RejectAdvertisement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/UpdateAdvertisement.
        /// </summary>
        public static string UpdateAdvertisement {
            get {
                return ResourceManager.GetString("UpdateAdvertisement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/UpdateEmployee.
        /// </summary>
        public static string UpdateEmployee {
            get {
                return ResourceManager.GetString("UpdateEmployee", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://localhost:44364/APIEmployee/Verification.
        /// </summary>
        public static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
    }
}
